//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notesmarketplaceEntities : DbContext
    {
        public notesmarketplaceEntities()
            : base("name=notesmarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDownload> tblDownloads { get; set; }
        public virtual DbSet<tblManageCountry> tblManageCountries { get; set; }
        public virtual DbSet<tblManageNoteCategory> tblManageNoteCategories { get; set; }
        public virtual DbSet<tblManageNoteType> tblManageNoteTypes { get; set; }
        public virtual DbSet<tblNoteAttachement> tblNoteAttachements { get; set; }
        public virtual DbSet<tblNoteDetail> tblNoteDetails { get; set; }
        public virtual DbSet<tblNoteReportedIsuue> tblNoteReportedIsuues { get; set; }
        public virtual DbSet<tblNoteReview> tblNoteReviews { get; set; }
        public virtual DbSet<tblReferenceData> tblReferenceDatas { get; set; }
        public virtual DbSet<tblSystemConfig> tblSystemConfigs { get; set; }
        public virtual DbSet<tblUserProfile> tblUserProfiles { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
