//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDownload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDownload()
        {
            this.tblNoteReportedIsuues = new HashSet<tblNoteReportedIsuue>();
            this.tblNoteReviews = new HashSet<tblNoteReview>();
        }
    
        public int id { get; set; }
        public int noteID { get; set; }
        public int seller { get; set; }
        public int downloader { get; set; }
        public bool isSellerHasAllowedDownload { get; set; }
        public string attachementPath { get; set; }
        public Nullable<System.DateTime> attachementDownloadDate { get; set; }
        public bool isPaid { get; set; }
        public Nullable<decimal> purchasedPrice { get; set; }
        public string noteTitle { get; set; }
        public string noteCategory { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public bool isAttachmentDownloaded { get; set; }
    
        public virtual tblNoteDetail tblNoteDetail { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoteReportedIsuue> tblNoteReportedIsuues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoteReview> tblNoteReviews { get; set; }
    }
}
