//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoteReview
    {
        public int id { get; set; }
        public int noteID { get; set; }
        public int reviewedByID { get; set; }
        public int againstDownloadID { get; set; }
        public decimal rating { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public bool isActive { get; set; }
    
        public virtual tblDownload tblDownload { get; set; }
        public virtual tblNoteDetail tblNoteDetail { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
