//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class tblNoteDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNoteDetail()
        {
            this.tblDownloads = new HashSet<tblDownload>();
            this.tblNoteAttachements = new HashSet<tblNoteAttachement>();
            this.tblNoteReportedIsuues = new HashSet<tblNoteReportedIsuue>();
            this.tblNoteReviews = new HashSet<tblNoteReview>();
        }

        public int id { get; set; }

        [Required]
        public int sellerID { get; set; }

        [Required]
        public int status { get; set; }

        [Required]
        public int actionedBy { get; set; }
        public string adminRemark { get; set; }

        [Required]
        public string noteTitle { get; set; }
        public string notePicture { get; set; }

        [Required]
        public int noteCategory { get; set; }
        public string noteUniversity { get; set; }
        public Nullable<int> noteType { get; set; }

        [Required]
        public string description { get; set; }
        public Nullable<int> numberOfPage { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public Nullable<int> country { get; set; }
        public string courseName { get; set; }
        public string courseCode { get; set; }
        public string professor { get; set; }

        [Required]
        public bool isPaid { get; set; }
        public Nullable<decimal> sellingPrice { get; set; }
        public string notePreview { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }

        [Required]
        public bool isActive { get; set; }

        [Required]
        public string filePath { get; set; }

        public bool isNoteDetailSet { get; set; }

        public HttpPostedFileBase imgFile { get; set; }

        public HttpPostedFileBase pdfFile { get; set; }

        public HttpPostedFileBase notepreviewFile { get; set; }

        public string SelectedRadioButtonValue { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDownload> tblDownloads { get; set; }
        public virtual tblManageNoteCategory tblManageNoteCategory { get; set; }
        public virtual tblManageNoteType tblManageNoteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoteAttachement> tblNoteAttachements { get; set; }
        public virtual tblReferenceData tblReferenceData { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoteReportedIsuue> tblNoteReportedIsuues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoteReview> tblNoteReviews { get; set; }
    }
}
