//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemConfig
    {
        public int id { get; set; }
        public string supportEmailID { get; set; }
        public string emailForEvent { get; set; }
        public string fbURL { get; set; }
        public string twitterURL { get; set; }
        public string linkedinURL { get; set; }
        public string defaultNoteImage { get; set; }
        public string defaultProfilePicture { get; set; }
        public string supportPhoneNo { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public bool isActive { get; set; }
    }
}
